### ISSUE TITLE
스터디 시작

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/FE_study#1]
추석이 끝나고 10월 셋째주 부터 시작해요 :)
9월 마지막 주에는 모든 논의사항이 결정되고 스터디 신청(및 도서 구매)을 할 예정입니다.

**Comment by BillionaireDY** [comment]
좋습니다. 👍🏽

**Comment by JaeYeopHan** [comment]
요일이 월 / 수인 관계로 10월 셋째주 월요일인 **10월 16일**이 스터디 첫주차가 됩니다 :)
