### ISSUE TITLE
회고

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/FE_study#15]
Vue 스터디 회고

**Comment by nablyy** [comment]
## 좋았던 점
- 프론트 쪽은 하나도 모르는데 새로운 것을 배우고 훑어볼 수 있어서 좋았다. 
- 뷰에 관련된 책을 얻고 읽어볼 수 있었다.
- 랜덤 발표여서 확실히 더 공부를 많이 했다. 랜덤 발표아니었으면 발표하는 때 빼고 아예 공부 안하고 왔을 것 같다.

## 아쉬웠던 점
- 뒤로 가면 갈수록 연말이라 너무 바빠서 스터디에 대한 의욕을 잃었다.
- 뒤로 가면 갈수록 루즈해졌던거 같다.

**Comment by soonderella9** [comment]
vue.js 뿐만 아니라 ES6등 전반적으로 JavaScrip와 FE에 대해서 배워 볼 수 있는 기회였습니다.
하지만 실습이나 직접 해보는 것까지 스터디에서 하지는 않았기 때문에 개인적인 노력이 더 필요했으나 많이 부족했던 점이 아쉬웠습니다.

**Comment by JaeYeopHan** [comment]
#### 좋았던 점
* 밥을 같이 먹을 수 있었다.
* 조금이라도 친해졌다.
* 책 이득

#### 아쉬웠던 점
* 관심사가 각자 다른데, 스터디 주제가 한 쪽 주제로 편향되어 있었기 때문에 스터디에 집중하기는 좀 힘들었다.
* 서로 일정이 조금씩 있었다.

#### TODO
* 공부는 각자하는 걸로
* 같이 할 거면 공통 관심사로 진행하기

**Comment by binDongKim** [comment]
- 그날그날 랜덤으로 선출된 개개인이 강의하는 방식으로 진행했기 때문에, 모든 구성원이 (최대한)준비를 하게끔해서 좋았어요.
- 사이드프로젝트 진행하지 못한점 아쉬웠어요.

**Comment by BillionaireDY** [comment]
## 좋았던 부분.
1. 설명을 준비하면서 내가 더 배울 수 있었다.
2. 내가 몰랐던 좋은 스킬들을 알 수 있었다.
3. ES6 파트 때 토론식(?) 스터디가 너무 좋았다.

## 아쉬웠던 부분.
1. 입사초반이라 들어오는 정보혹은 업무가 너무 많아서 스터디 참여에 집중하기에 힘들었다. (부담스럼)
2. 배고픈 시간대라 고통스러웠다.

## 앞으로~
1. 조금 여유로울 때 스터디를 한다면 최고의 시너지효과가있을듯.
