### ISSUE TITLE
스터디 기획안

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/FE_study#2]
### 요일 / 시간 선정
* 요일 : 월 / 화 / 수 / 목 / 금
* 시간 : 출근시간 전(08:00 ~ 10:00) / 점심시간(12:00 ~ 14:00) / 퇴근 후(19:00 ~ 21:00) 

### 스터디 형식
* 정해진 건 없고 어떤 방식으로 진행할 지 결정
  * 돌아가면서 강의하는 형식, 프로젝트 형식, 강의를 듣는 형식, + 하이브리드
* (원하는 교재 or 강의가 있다면 추가 댓글)

위 두 가지 사항에 대해 comment 달기

**Comment by JaeYeopHan** [comment]
* [Vue.js Quick Start](http://www.yes24.com/24/goods/45091747?scode=032&OzSrank=1)
* [쉽고 빠르게 배우는 Vue.js 2.0 프로그래밍](http://www.yes24.com/24/goods/44271600?scode=032&OzSrank=2)
* [Vue.js 2 시작하기](http://www.yes24.com/24/goods/40951100?scode=032&OzSrank=3)

**Comment by JaeYeopHan** [comment]
### 강의 목록
* [Udemy - Vue JS 2 - The Complete Guid](https://www.udemy.com/vuejs-2-the-complete-guide/)
  * udemy에서 제일 잘 나가는 vue 강의

**Comment by BillionaireDY** [comment]
### 요일 / 시간 선정

  * 요일 : 화 / 목 
    * (주 2회 유동적으로도 괜찮을 것 같습니다.)
  * 시간 :  점심시간(12:00 ~ 14:00) 선호합니다.

### 스터디방식
  * 강의를 보는 방법을 선호합니다. 
  * 책은 지정 도서를 구입한뒤 자유롭게 토론하고 의견나눴으면 좋겠습니다.

**Comment by JaeYeopHan** [comment]
#### 요일 및 시간
* 요일은 거의 상관없을 것 같습니다.
* 점심시간이 좋겠죠?

#### 스터디 방식
* 책으로 본다면, Vue.js의 기본적인 내용에 대해서는 딱히 의견을 나눌 것이 없다고 생각합니다. 그래서 일정 범위 학습을 해오고, 만나는 스터디 시간에 이해가 안되는 부분에 대해서 서로 이야기를 나눴으면 좋겠습니다.
* 개인적으로 제대로 학습하려면 누군가에게 알려주는 방식이 되어야 한다고 생각하는데요, 차라리 일정 범위를 각자 공부해오고 스터디 시간에 만나서 랜덤으로 뽑히는 사람이 그날 강의를 하는 형식도 괜찮을 것 같습니다. 하다 막히면 서로 도와주는 형식의 스터디... (해봤는데 스릴있고 재밌었습니다.)
* 강의 형식은 자칫 스터디가 루즈해지지 않을까 걱정입니다.

#### 기타
* 사이드 프로젝트에 적극 찬성합니당 :) 이 부분은 필수적인 것은 아니므로 스터디원 모두가 하는 것보단 개인적으로 진행하는 것이 좋을 듯 싶습니다.
* 완전 프로젝트가 아니고 Vue에 대한 기본적인 학습을 위해서라면 간단한 TODO application을 만들어보는 것도 좋을 것 같습니다. 지금 개인적으로 진행하고 있는데, 스터디가 시작할 때 쯤이면 다 만들어질 것 같습니다. (일단 공유)
  * [vue-todo-tutorial](https://github.com/JaeYeopHan/vue-todo-tutorial)

**Comment by BillionaireDY** [comment]
####  요일 및 시간
  * 이견 없습니다. :)

#### 스터디방식
  * 책 : 말씀하신 부분에 동의합니다. 그러면 책을 하나 같은걸로 선정하는게 맞겠죠?
    * + 생각해보니깐, 각자 사고싶은 책사서 다른책에 없는 내용(거의다 비슷하겠지만)을 공유히는 것도 좋을것 같습니다.
  * 서로강의해주기 : 참신한 방법이네요! 재밌을것 같습니다.

#### 기타
  * 사이드프로젝트 : 팀원들 시간상 개인프로젝트가 진행하는데 무리없을 것 같네요. 동의합니다.

**Comment by binDongKim** [comment]
# 요일 및 시간
- 요일: 일주일에 두번하는게 좋을 것 같구요, 요일은 최소2일정도 텀이 있었으면 좋겠어요(ex. 월, 목) 텀이 하루면 준비나 진행상황이 많이 진척되지않을것 같아서요. 저도 시간은 점심시간 선호합니다 :D 

# 스터디 형식
- "서로 강의해주기" 재밌을 것 같아요!
- 저도 일단은 강의를 보는게 낫지 않을까 하는 생각은 들어요. 루즈해질 수 있긴 한데, 일단은 아무것도 모르는 상황에서 책부터 보는것보단 강의가 아주 미세하지만 좀더 인터렉션이 있으니까 좀 더 낫지않나 생각해봅니다.
- 책 선정에 관해서는 도윤님 말씀하신 것처럼 서로 다른책으로 해서 다른관점으로 쓰인부분이 있으면 공유해보는 것도 재밌을것 같습니다.

# 기타
- 사이드 프로젝트 하는것 적극 찬성이구요, 단, 강의/진도가 어느정도 나갔을 때 진행되었으면 좋겠어요. 그리고 주기적으로 프로젝트 진행중에 코드리뷰도 있었으면 좋겠습니다.

# 논외
- 아까 잠깐 나온 얘기인데, Angular 스터디에 대해선 어떻게 생각하시나요? 그냥 두분 의견 궁금해서 물어봅니당

**Comment by JaeYeopHan** [comment]
#### 요일 / 시간
* 월 / 목, 점심시간 (주 2회) 진행으로 정리하면 좋을 것 같네요 :)
  * 11시 55분 쯤에 만나서 밥먹으로 내려가고 커피 사서 올라오면 되겠네요!

#### 스터디 형식
* 서로 강의해주기 반응이 좋아 스터디 형식에 포함시킵니다.

* 강의에 대한 니즈도 있는 것 같아 주 2회니 하루씩 나눠서 진행하면 될 것 같습니다.
  * 월(강의 수강) / 목(서로 강의해주기)

* 서로 강의해주기 구체적인 내용
  * 스터디 시작하는 시점에, 참가한 인원을 기준으로 랜덤 뽑기를 통해 그날 강의자를 선정하여 학습해오기로 한 범위에 대해 강의자가 강의를 진행합니다.
  * 일반적인 강의가 아닌 서로 이해가 안됬던 부분을 이야기하는 형식으로 진행됩니다.
  * 강의자는 그날 스터디를 이끌어가는 형식이 되겠네요 :)

* 교재는 아무래도 통일하는게 나을 것 같다는게 제 생각인데요, 학습해오는 일정 범위를 선정하는데 특정 교재가 중심이 될텐데, 해당 교재를 맡은 사람은 편하겠지만 그렇지 않은 교재의 경우 순서가 뒤바뀌는 경우가 발생할 것 같습니다.
  * 그런 의미에서 Quick Start Vue.js 책으로 통일하는건 어떤가요? (보고 있는데 ES6, Webpack도 다루고 있어서 JS를 잘 몰라도 이 교재로 충분히 함께 할 수 있을 것 같습니다.
  * Quick Start Vue.js 책으로 통일된다면 제가 이 교재를 기준으로 스터디 계획을 세워보겠습니다.

#### 기타
* 사이드 프로젝트도 의견이 통일되었네요 :)
  * @binDongKim 말대로 어느정도 진행된 후, 사이드 프로젝트 진행합니다! 개인적인 생각으로는 Vuex 들어가기 전, 들어가면 좋을 것 같아요!
* Angular... :)

**Comment by KeonHee** [comment]
### 지나가는 행인
 - Vue는 React처럼 어렵지가 않아서 인강보다는 책사서 공부하고 서로 강의해주고 바로 사이드 프로젝트 진행하는 것을 추천합니다,,,
 - 강의듣고 강의해주고 책보고 사이드프로젝트까지 하는건 오버인듯

**Comment by JaeYeopHan** [comment]
> 지나가는 행인은 그냥 지나가주세요 :)

강의듣는 부분은 이해가 되지만 서로 강의해주면 재밌을 것 같은데 :) 그리고 사이드 프로젝트는 TODO 만드는 건데 별로 어렵지 않을거 같은데요??ㅋㅋ

**Comment by binDongKim** [comment]
## 요일
- 생각해보니 매주 목요일 점심엔 저희팀 점심밖으로 먹으러가는날이라 다른분들 괜찮으면 *화/금* 건의해봅니다..
## 스터디형식
- 교재 Quick Start Vue.js 책 통일 동의합니당
## 기타
- Angular관련: @JaeYeopHan 동의합니당

> 지나가는 행인은 가던 길 계속 가주세요 :)

**Comment by Nablyy** [comment]
### 요일
- 화목은 점심에 스터디가 예정되어있어서 안돼요! **월/수**나 **수/금**을 추천해봅니다.

### 스터디 형식
- 서로 강의해주기: 각자 공부하고 랜덤 강의하는거 재밌어보여요! 어차피 PT자료도 제출해야하니까 더 좋은거 같아요.
- 강의 듣기: 인강은 듣고 싶은 사람만 따로 개인시간에 듣는게 좋을 것 같아요.

### 도서
- Vue.js Quick Start 통일: 찬성합니다.

### 기타
- 사이드 프로젝트: 찬성합니다.

**Comment by soonderella9** [comment]
요일
----
- 화목 스터디가 있어서 다른날 가능합니다.

스터디 형식
----
- 저는 강의 보는 형식을 더 선호합니다.

도서
----
- Vue.js Quick Start 통일: 찬성합니다

기타
----
- 사이드 프로젝트: 어렵지 않다면 좋습니다.

**Comment by soonderella9** [comment]
요일
----
- 화목 스터디 때문에 다른날이 좋습니다.

스터디 형식
----
- 저는 강의를 듣는 것을 더 선호합니다.

도서
----
- 도서 통일하는거 찬성합니다.

기타
----
- 사이드프로젝트 어렵지 않다면 찬성합니다.

**Comment by Nablyy** [comment]
### 기타
저는 Vue.js 끝나고 Angular 스터디하시면 참여할 생각이 있어요! 했으면 좋겠어요~

**Comment by JaeYeopHan** [comment]
## 논의사항 정리
### 요일 및 시간
* 월/수 점심시간(12:00 ~ 14:00)
### 스터디 형식
* 교재: Vue.js Quick Start
  * 제가 갖고 있으니 궁금한 사람은 와서 보셔도 됩니다.
* 랜덤 강의 vs 강의 듣기 (추가로 논의)
### 사이드 프로젝트
* 개인적으로 진행.
* 진행하는 사람끼리 코드리뷰 진행.

**Comment by JaeYeopHan** [comment]
## 10월 18일 OT
### 시간
* 월 / 수
  * 점심먹고 & 점심 먹기 전 (다음 주에 결정)
### 스터디 형식
* 주차별(월/수) 랜덤 pick!
* 회의실 예약
  * 전 주차 발표자가 다음 주 회의실 잡기.
