### ISSUE TITLE
스터디 연장

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/FE_study#4]
Vue.js 가 끝나고 Nuxt.js 스터디로 연장하는건 어때요? nuxt도 관심이 있어서요! :)
[Nuxt.js Github repository](https://github.com/nuxt/nuxt.js)

**Comment by binDongKim** [comment]
좋습니다 👍

**Comment by BillionaireDY** [comment]
Nuxt.js 는 한번 훑어보고 다음주 월요일 (0925) 에 코멘트를 달도록 하겠습니다.
처음보는 거라서 ㅎㅎㅎ
